In [2]:
import pandas as pd
import re
df = pd.read_csv("datasets/presidents.csv")
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

In [48]:
df['FirstName'] = df['President'].str.extract('(\w+)')
df['MiddleName'] = df['President'].str.extract('(?:[\w]+\s)(\w+[.]?)(?:\s\w+)')
df['LastName'] = df['President'].str.extract('([\w-]+$)')
df[['President','FirstName','MiddleName','LastName']]

                President   FirstName MiddleName    LastName
0       George Washington      George        NaN  Washington
1              John Adams        John        NaN       Adams
2        Thomas Jefferson      Thomas        NaN   Jefferson
3           James Madison       James        NaN     Madison
4            James Monroe       James        NaN      Monroe
5       John Quincy Adams        John     Quincy       Adams
6          Andrew Jackson      Andrew        NaN     Jackson
7        Martin Van Buren      Martin        Van       Buren
8     William H. Harrison     William         H.    Harrison
9              John Tyler        John        NaN       Tyler
10          James K. Polk       James         K.        Polk
11         Zachary Taylor     Zachary        NaN      Taylor
12       Millard Fillmore     Millard        NaN    Fillmore
13        Franklin Pierce    Franklin        NaN      Pierce
14         James Buchanan       James        NaN    Buchanan
15        Abraham Lincoln     Abraham        NaN     Lincoln
16         Andrew Johnson      Andrew        NaN     Johnson
17       Ulysses S. Grant     Ulysses         S.       Grant
18    Rutherford B. Hayes  Rutherford         B.       Hayes
19      James A. Garfield       James         A.    Garfield
20      Chester A. Arthur     Chester         A.      Arthur
21       Grover Cleveland      Grover        NaN   Cleveland
22      Benjamin Harrison    Benjamin        NaN    Harrison
23       Grover Cleveland      Grover        NaN   Cleveland
24       William McKinley     William        NaN    McKinley
25     Theodore Roosevelt    Theodore        NaN   Roosevelt
26        William H. Taft     William         H.        Taft
27         Woodrow Wilson     Woodrow        NaN      Wilson
28      Warren G. Harding      Warren         G.     Harding
29        Calvin Coolidge      Calvin        NaN    Coolidge
30         Herbert Hoover     Herbert        NaN      Hoover
31  Franklin D. Roosevelt    Franklin         D.   Roosevelt
32        Harry S. Truman       Harry         S.      Truman
33   Dwight D. Eisenhower      Dwight         D.  Eisenhower
34        John F. Kennedy        John         F.     Kennedy
35      Lyndon B. Johnson      Lyndon         B.     Johnson
36          Richard Nixon     Richard        NaN       Nixon
37            Gerald Ford      Gerald        NaN        Ford
38           Jimmy Carter       Jimmy        NaN      Carter
39          Ronald Reagan      Ronald        NaN      Reagan
40      George H. W. Bush      George         H.        Bush
41           Bill Clinton        Bill        NaN     Clinton
42         George W. Bush      George         W.        Bush
43           Barack Obama      Barack        NaN       Obama

In [10]:
df['Born'] = df['Born'].str.extract('(\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['Born'] = pd.to_datetime(df['Born'])
df

AttributeError: Can only use .str accessor with string values!

In [12]:
df['Died'] = df['Died'].str.extract('(\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['Died'] = pd.to_datetime(df['Died'])

In [13]:
df

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,FirstName,MiddleName,LastName
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days",1799-12-14,"67 years, 295 days",George,NaN,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days",1826-07-04,"90 years, 247 days",John,NaN,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days",1826-07-04,"83 years, 82 days",Thomas,NaN,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days",1836-06-28,"85 years, 104 days",James,NaN,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days",1831-07-04,"73 years, 67 days",James,NaN,Monroe
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days",1848-02-23,"80 years, 227 days",John,Quincy,Adams
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days",1845-06-08,"78 years, 85 days",Andrew,NaN,Jackson
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days",1862-07-24,"79 years, 231 days",Martin,Van,Buren
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,1841-04-04,"68 years, 54 days",William,H.,Harrison
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days",1862-01-18,"71 years, 295 days",John,NaN,Tyler
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,1849-06-15,"53 years, 225 days",James,K.,Polk
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,1850-07-09,"65 years, 227 days",Zachary,NaN,Taylor
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days",1874-03-08,"74 years, 60 days",Millard,NaN,Fillmore
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days",1869-10-08,"64 years, 319 days",Franklin,NaN,Pierce
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days",1868-06-01,"77 years, 39 days",James,NaN,Buchanan
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,1865-04-15,"56 years, 62 days",Abraham,NaN,Lincoln
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days",1875-07-31,"66 years, 214 days",Andrew,NaN,Johnson
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days",1885-07-23,"63 years, 87 days",Ulysses,S.,Grant
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days",1893-01-17,"70 years, 105 days",Rutherford,B.,Hayes
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,1881-09-19,"49 years, 304 days",James,A.,Garfield
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days",1886-11-18,"57 years, 44 days",Chester,A.,Arthur
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days",1901-03-13,"67 years, 205 days",Benjamin,NaN,Harrison
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,1901-09-14,"58 years, 228 days",William,NaN,McKinley
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days",1919-01-06,"60 years, 71 days",Theodore,NaN,Roosevelt
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days",1930-03-08,"72 years, 174 days",William,H.,Taft
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days",1924-02-03,"67 years, 37 days",Woodrow,NaN,Wilson
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,1923-08-02,"57 years, 273 days",Warren,G.,Harding
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days",1933-01-05,"60 years, 185 days",Calvin,NaN,Coolidge
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days",1964-10-20,"90 years, 71 days",Herbert,NaN,Hoover
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,1945-04-12,"63 years, 72 days",Franklin,D.,Roosevelt
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days",1972-12-26,"88 years, 232 days",Harry,S.,Truman
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days",1969-03-28,"78 years, 165 days",Dwight,D.,Eisenhower
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,1963-11-22,"46 years, 177 days",John,F.,Kennedy
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days",1973-01-22,"64 years, 148 days",Lyndon,B.,Johnson
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days",1994-04-22,"81 years, 103 days",Richard,NaN,Nixon
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days",2006-12-26,"93 years, 165 days",Gerald,NaN,Ford
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",NaT,"94 years, 286 days",Jimmy,NaN,Carter
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days",2004-06-05,"93 years, 120 days",Ronald,NaN,Reagan
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days",2018-11-30,"94 years, 171 days",George,H.,Bush
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",NaT,"72 years, 329 days",Bill,NaN,Clinton
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",NaT,"73 years, 8 days",George,W.,Bush
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",NaT,"57 years, 344 days",Barack,NaN,Obama

In [32]:
r = '57 years, 67 daysApr 30, 1789'
re.findall('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,2})(?:\s\w{1,4})(\w{1,3}\s\d{1,2}[,]\s\d{1,4})',r)

['Apr 30, 1789']

In [38]:
df['Start_Year_of_Presidency'] = df['Age atstart of presidency'].str.extract('(\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})(?:\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['Start_Days_of_Presidency'] = df['Age atstart of presidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(\d{1,3})(?:\s\w{1,4})(?:\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['Start_Date_of_Presidency'] = df['Age atstart of presidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})(\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['Start_Date_of_Presidency'] = pd.to_datetime(df['Start_Date_of_Presidency'])
df

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,FirstName,MiddleName,LastName,Start_Year_of_Presidency,Start_Days_of_Presidency,Start_Date_of_Presidency
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days",1799-12-14,"67 years, 295 days",George,NaN,Washington,57,67,1789-04-30
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days",1826-07-04,"90 years, 247 days",John,NaN,Adams,61,125,1797-03-04
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days",1826-07-04,"83 years, 82 days",Thomas,NaN,Jefferson,57,325,1801-03-04
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days",1836-06-28,"85 years, 104 days",James,NaN,Madison,57,353,1809-03-04
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days",1831-07-04,"73 years, 67 days",James,NaN,Monroe,58,310,1817-03-04
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days",1848-02-23,"80 years, 227 days",John,Quincy,Adams,57,236,1825-03-04
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days",1845-06-08,"78 years, 85 days",Andrew,NaN,Jackson,61,354,1829-03-04
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days",1862-07-24,"79 years, 231 days",Martin,Van,Buren,54,89,1837-03-04
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,1841-04-04,"68 years, 54 days",William,H.,Harrison,68,23,1841-03-04
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days",1862-01-18,"71 years, 295 days",John,NaN,Tyler,51,6,1841-04-04
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,1849-06-15,"53 years, 225 days",James,K.,Polk,49,122,1845-03-04
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,1850-07-09,"65 years, 227 days",Zachary,NaN,Taylor,64,100,1849-03-04
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days",1874-03-08,"74 years, 60 days",Millard,NaN,Fillmore,50,183,1850-07-09
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days",1869-10-08,"64 years, 319 days",Franklin,NaN,Pierce,48,101,1853-03-04
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days",1868-06-01,"77 years, 39 days",James,NaN,Buchanan,65,315,1857-03-04
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,1865-04-15,"56 years, 62 days",Abraham,NaN,Lincoln,52,20,1861-03-04
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days",1875-07-31,"66 years, 214 days",Andrew,NaN,Johnson,56,107,1865-04-15
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days",1885-07-23,"63 years, 87 days",Ulysses,S.,Grant,46,311,1869-03-04
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days",1893-01-17,"70 years, 105 days",Rutherford,B.,Hayes,54,151,1877-03-04
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,1881-09-19,"49 years, 304 days",James,A.,Garfield,49,105,1881-03-04
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days",1886-11-18,"57 years, 44 days",Chester,A.,Arthur,51,349,1881-09-19
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,47,351,1885-03-04
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days",1901-03-13,"67 years, 205 days",Benjamin,NaN,Harrison,55,196,1889-03-04
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,55,351,1893-03-04
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,1901-09-14,"58 years, 228 days",William,NaN,McKinley,54,34,1897-03-04
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days",1919-01-06,"60 years, 71 days",Theodore,NaN,Roosevelt,42,322,1901-09-14
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days",1930-03-08,"72 years, 174 days",William,H.,Taft,51,170,1909-03-04
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days",1924-02-03,"67 years, 37 days",Woodrow,NaN,Wilson,56,66,1913-03-04
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,1923-08-02,"57 years, 273 days",Warren,G.,Harding,55,122,1921-03-04
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days",1933-01-05,"60 years, 185 days",Calvin,NaN,Coolidge,51,29,1923-08-02
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days",1964-10-20,"90 years, 71 days",Herbert,NaN,Hoover,54,206,1929-03-04
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,1945-04-12,"63 years, 72 days",Franklin,D.,Roosevelt,51,33,1933-03-04
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days",1972-12-26,"88 years, 232 days",Harry,S.,Truman,60,339,1945-04-12
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days",1969-03-28,"78 years, 165 days",Dwight,D.,Eisenhower,62,98,1953-01-20
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,1963-11-22,"46 years, 177 days",John,F.,Kennedy,43,236,1961-01-20
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days",1973-01-22,"64 years, 148 days",Lyndon,B.,Johnson,55,87,1963-11-22
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days",1994-04-22,"81 years, 103 days",Richard,NaN,Nixon,56,11,1969-01-20
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days",2006-12-26,"93 years, 165 days",Gerald,NaN,Ford,61,26,1974-08-09
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",NaT,"94 years, 286 days",Jimmy,NaN,Carter,52,111,1977-01-20
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days",2004-06-05,"93 years, 120 days",Ronald,NaN,Reagan,69,349,1981-01-20
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days",2018-11-30,"94 years, 171 days",George,H.,Bush,64,222,1989-01-20
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",NaT,"72 years, 329 days",Bill,NaN,Clinton,46,154,1993-01-20
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",NaT,"73 years, 8 days",George,W.,Bush,54,198,2001-01-20
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",NaT,"57 years, 344 days",Barack,NaN,Obama,47,169,2009-01-20

In [39]:
df['End_Year_of_Presidency'] = df['Age atend of presidency'].str.extract('(\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})(?:\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['End_Days_of_Presidency'] = df['Age atend of presidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(\d{1,3})(?:\s\w{1,4})(?:\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['End_Date_of_Presidency'] = df['Age atend of presidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})(\w{1,3}\s\d{1,2}[,]\s\d{1,4})')
df['End_Date_of_Presidency'] = pd.to_datetime(df['End_Date_of_Presidency'])
df

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,FirstName,MiddleName,LastName,Start_Year_of_Presidency,Start_Days_of_Presidency,Start_Date_of_Presidency,End_Year_of_Presidency,End_Days_of_Presidency,End_Date_of_Presidency
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days",1799-12-14,"67 years, 295 days",George,NaN,Washington,57,67,1789-04-30,65,10,1797-03-04
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days",1826-07-04,"90 years, 247 days",John,NaN,Adams,61,125,1797-03-04,65,125,1801-03-04
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days",1826-07-04,"83 years, 82 days",Thomas,NaN,Jefferson,57,325,1801-03-04,65,325,1809-03-04
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days",1836-06-28,"85 years, 104 days",James,NaN,Madison,57,353,1809-03-04,65,353,1817-03-04
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days",1831-07-04,"73 years, 67 days",James,NaN,Monroe,58,310,1817-03-04,66,310,1825-03-04
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days",1848-02-23,"80 years, 227 days",John,Quincy,Adams,57,236,1825-03-04,61,236,1829-03-04
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days",1845-06-08,"78 years, 85 days",Andrew,NaN,Jackson,61,354,1829-03-04,69,354,1837-03-04
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days",1862-07-24,"79 years, 231 days",Martin,Van,Buren,54,89,1837-03-04,58,89,1841-03-04
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,1841-04-04,"68 years, 54 days",William,H.,Harrison,68,23,1841-03-04,NaN,NaN,NaT
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days",1862-01-18,"71 years, 295 days",John,NaN,Tyler,51,6,1841-04-04,54,340,1845-03-04
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,1849-06-15,"53 years, 225 days",James,K.,Polk,49,122,1845-03-04,53,122,1849-03-04
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,1850-07-09,"65 years, 227 days",Zachary,NaN,Taylor,64,100,1849-03-04,65,227,1850-07-09
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days",1874-03-08,"74 years, 60 days",Millard,NaN,Fillmore,50,183,1850-07-09,53,56,1853-03-04
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days",1869-10-08,"64 years, 319 days",Franklin,NaN,Pierce,48,101,1853-03-04,52,101,1857-03-04
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days",1868-06-01,"77 years, 39 days",James,NaN,Buchanan,65,315,1857-03-04,69,315,1861-03-04
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,1865-04-15,"56 years, 62 days",Abraham,NaN,Lincoln,52,20,1861-03-04,56,62,1865-04-15
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days",1875-07-31,"66 years, 214 days",Andrew,NaN,Johnson,56,107,1865-04-15,60,65,1869-03-04
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days",1885-07-23,"63 years, 87 days",Ulysses,S.,Grant,46,311,1869-03-04,54,311,1877-03-04
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days",1893-01-17,"70 years, 105 days",Rutherford,B.,Hayes,54,151,1877-03-04,58,151,1881-03-04
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,1881-09-19,"49 years, 304 days",James,A.,Garfield,49,105,1881-03-04,49,304,1881-09-19
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days",1886-11-18,"57 years, 44 days",Chester,A.,Arthur,51,349,1881-09-19,55,150,1885-03-04
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,47,351,1885-03-04,51,351,1889-03-04
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days",1901-03-13,"67 years, 205 days",Benjamin,NaN,Harrison,55,196,1889-03-04,59,196,1893-03-04
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,55,351,1893-03-04,59,351,1897-03-04
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,1901-09-14,"58 years, 228 days",William,NaN,McKinley,54,34,1897-03-04,58,228,1901-09-14
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days",1919-01-06,"60 years, 71 days",Theodore,NaN,Roosevelt,42,322,1901-09-14,50,128,1909-03-04
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days",1930-03-08,"72 years, 174 days",William,H.,Taft,51,170,1909-03-04,55,170,1913-03-04
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days",1924-02-03,"67 years, 37 days",Woodrow,NaN,Wilson,56,66,1913-03-04,64,66,1921-03-04
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,1923-08-02,"57 years, 273 days",Warren,G.,Harding,55,122,1921-03-04,57,273,1923-08-02
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days",1933-01-05,"60 years, 185 days",Calvin,NaN,Coolidge,51,29,1923-08-02,56,243,1929-03-04
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days",1964-10-20,"90 years, 71 days",Herbert,NaN,Hoover,54,206,1929-03-04,58,206,1933-03-04
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,1945-04-12,"63 years, 72 days",Franklin,D.,Roosevelt,51,33,1933-03-04,63,72,1945-04-12
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days",1972-12-26,"88 years, 232 days",Harry,S.,Truman,60,339,1945-04-12,68,257,1953-01-20
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days",1969-03-28,"78 years, 165 days",Dwight,D.,Eisenhower,62,98,1953-01-20,70,98,1961-01-20
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,1963-11-22,"46 years, 177 days",John,F.,Kennedy,43,236,1961-01-20,46,177,1963-11-22
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days",1973-01-22,"64 years, 148 days",Lyndon,B.,Johnson,55,87,1963-11-22,60,146,1969-01-20
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days",1994-04-22,"81 years, 103 days",Richard,NaN,Nixon,56,11,1969-01-20,61,212,1974-08-09
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days",2006-12-26,"93 years, 165 days",Gerald,NaN,Ford,61,26,1974-08-09,63,190,1977-01-20
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",NaT,"94 years, 286 days",Jimmy,NaN,Carter,52,111,1977-01-20,56,111,1981-01-20
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days",2004-06-05,"93 years, 120 days",Ronald,NaN,Reagan,69,349,1981-01-20,77,349,1989-01-20
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days",2018-11-30,"94 years, 171 days",George,H.,Bush,64,222,1989-01-20,68,222,1993-01-20
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",NaT,"72 years, 329 days",Bill,NaN,Clinton,46,154,1993-01-20,54,154,2001-01-20
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",NaT,"73 years, 8 days",George,W.,Bush,54,198,2001-01-20,62,198,2009-01-20
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",NaT,"57 years, 344 days",Barack,NaN,Obama,47,169,2009-01-20,55,169,2017-01-20

In [40]:
df['years_Post-presidencytimespan'] = df['Post-presidencytimespan'].str.extract('(\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})')
df['Days_Post-presidencytimespan'] = df['Post-presidencytimespan'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(\d{1,3})(?:\s\w{1,4})')
df

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,FirstName,MiddleName,LastName,Start_Year_of_Presidency,Start_Days_of_Presidency,Start_Date_of_Presidency,End_Year_of_Presidency,End_Days_of_Presidency,End_Date_of_Presidency,years_Post-presidencytimespan,Days_Post-presidencytimespan
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days",1799-12-14,"67 years, 295 days",George,NaN,Washington,57,67,1789-04-30,65,10,1797-03-04,2,285
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days",1826-07-04,"90 years, 247 days",John,NaN,Adams,61,125,1797-03-04,65,125,1801-03-04,25,122
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days",1826-07-04,"83 years, 82 days",Thomas,NaN,Jefferson,57,325,1801-03-04,65,325,1809-03-04,17,122
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days",1836-06-28,"85 years, 104 days",James,NaN,Madison,57,353,1809-03-04,65,353,1817-03-04,19,116
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days",1831-07-04,"73 years, 67 days",James,NaN,Monroe,58,310,1817-03-04,66,310,1825-03-04,6,122
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days",1848-02-23,"80 years, 227 days",John,Quincy,Adams,57,236,1825-03-04,61,236,1829-03-04,18,356
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days",1845-06-08,"78 years, 85 days",Andrew,NaN,Jackson,61,354,1829-03-04,69,354,1837-03-04,8,96
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days",1862-07-24,"79 years, 231 days",Martin,Van,Buren,54,89,1837-03-04,58,89,1841-03-04,21,142
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,1841-04-04,"68 years, 54 days",William,H.,Harrison,68,23,1841-03-04,NaN,NaN,NaT,NaN,NaN
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days",1862-01-18,"71 years, 295 days",John,NaN,Tyler,51,6,1841-04-04,54,340,1845-03-04,16,320
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,1849-06-15,"53 years, 225 days",James,K.,Polk,49,122,1845-03-04,53,122,1849-03-04,NaN,NaN
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,1850-07-09,"65 years, 227 days",Zachary,NaN,Taylor,64,100,1849-03-04,65,227,1850-07-09,NaN,NaN
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days",1874-03-08,"74 years, 60 days",Millard,NaN,Fillmore,50,183,1850-07-09,53,56,1853-03-04,21,4
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days",1869-10-08,"64 years, 319 days",Franklin,NaN,Pierce,48,101,1853-03-04,52,101,1857-03-04,12,218
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days",1868-06-01,"77 years, 39 days",James,NaN,Buchanan,65,315,1857-03-04,69,315,1861-03-04,7,89
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,1865-04-15,"56 years, 62 days",Abraham,NaN,Lincoln,52,20,1861-03-04,56,62,1865-04-15,NaN,NaN
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days",1875-07-31,"66 years, 214 days",Andrew,NaN,Johnson,56,107,1865-04-15,60,65,1869-03-04,6,149
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days",1885-07-23,"63 years, 87 days",Ulysses,S.,Grant,46,311,1869-03-04,54,311,1877-03-04,8,141
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days",1893-01-17,"70 years, 105 days",Rutherford,B.,Hayes,54,151,1877-03-04,58,151,1881-03-04,11,319
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,1881-09-19,"49 years, 304 days",James,A.,Garfield,49,105,1881-03-04,49,304,1881-09-19,NaN,NaN
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days",1886-11-18,"57 years, 44 days",Chester,A.,Arthur,51,349,1881-09-19,55,150,1885-03-04,1,259
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,47,351,1885-03-04,51,351,1889-03-04,4,0
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days",1901-03-13,"67 years, 205 days",Benjamin,NaN,Harrison,55,196,1889-03-04,59,196,1893-03-04,8,9
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]",1908-06-24,"71 years, 98 days",Grover,NaN,Cleveland,55,351,1893-03-04,59,351,1897-03-04,11,112
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,1901-09-14,"58 years, 228 days",William,NaN,McKinley,54,34,1897-03-04,58,228,1901-09-14,NaN,NaN
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days",1919-01-06,"60 years, 71 days",Theodore,NaN,Roosevelt,42,322,1901-09-14,50,128,1909-03-04,9,308
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days",1930-03-08,"72 years, 174 days",William,H.,Taft,51,170,1909-03-04,55,170,1913-03-04,17,4
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days",1924-02-03,"67 years, 37 days",Woodrow,NaN,Wilson,56,66,1913-03-04,64,66,1921-03-04,2,336
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,1923-08-02,"57 years, 273 days",Warren,G.,Harding,55,122,1921-03-04,57,273,1923-08-02,NaN,NaN
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days",1933-01-05,"60 years, 185 days",Calvin,NaN,Coolidge,51,29,1923-08-02,56,243,1929-03-04,3,307
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days",1964-10-20,"90 years, 71 days",Herbert,NaN,Hoover,54,206,1929-03-04,58,206,1933-03-04,31,230
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,1945-04-12,"63 years, 72 days",Franklin,D.,Roosevelt,51,33,1933-03-04,63,72,1945-04-12,NaN,NaN
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days",1972-12-26,"88 years, 232 days",Harry,S.,Truman,60,339,1945-04-12,68,257,1953-01-20,19,341
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days",1969-03-28,"78 years, 165 days",Dwight,D.,Eisenhower,62,98,1953-01-20,70,98,1961-01-20,8,67
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,1963-11-22,"46 years, 177 days",John,F.,Kennedy,43,236,1961-01-20,46,177,1963-11-22,NaN,NaN
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days",1973-01-22,"64 years, 148 days",Lyndon,B.,Johnson,55,87,1963-11-22,60,146,1969-01-20,4,2
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days",1994-04-22,"81 years, 103 days",Richard,NaN,Nixon,56,11,1969-01-20,61,212,1974-08-09,19,256
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days",2006-12-26,"93 years, 165 days",Gerald,NaN,Ford,61,26,1974-08-09,63,190,1977-01-20,29,340
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",NaT,"94 years, 286 days",Jimmy,NaN,Carter,52,111,1977-01-20,56,111,1981-01-20,38,175
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days",2004-06-05,"93 years, 120 days",Ronald,NaN,Reagan,69,349,1981-01-20,77,349,1989-01-20,15,137
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days",2018-11-30,"94 years, 171 days",George,H.,Bush,64,222,1989-01-20,68,222,1993-01-20,25,314
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",NaT,"72 years, 329 days",Bill,NaN,Clinton,46,154,1993-01-20,54,154,2001-01-20,18,175
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",NaT,"73 years, 8 days",George,W.,Bush,54,198,2001-01-20,62,198,2009-01-20,10,175
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",NaT,"57 years, 344 days",Barack,NaN,Obama,47,169,2009-01-20,55,169,2017-01-20,2,175

In [41]:
df['years_Age'] = df['Age'].str.extract('(\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(?:\d{1,3})(?:\s\w{1,4})')
df['Days_Age'] = df['Age'].str.extract('(?:\d{1,2})(?:\s)(?:\w{1,5})(?:[,])(?:\s)(\d{1,3})(?:\s\w{1,4})')
df

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,FirstName,MiddleName,...,Start_Year_of_Presidency,Start_Days_of_Presidency,Start_Date_of_Presidency,End_Year_of_Presidency,End_Days_of_Presidency,End_Date_of_Presidency,years_Post-presidencytimespan,Days_Post-presidencytimespan,years_Age,Days_Age
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days",1799-12-14,"67 years, 295 days",George,NaN,...,57,67,1789-04-30,65,10,1797-03-04,2,285,67,295
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days",1826-07-04,"90 years, 247 days",John,NaN,...,61,125,1797-03-04,65,125,1801-03-04,25,122,90,247
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days",1826-07-04,"83 years, 82 days",Thomas,NaN,...,57,325,1801-03-04,65,325,1809-03-04,17,122,83,82
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days",1836-06-28,"85 years, 104 days",James,NaN,...,57,353,1809-03-04,65,353,1817-03-04,19,116,85,104
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days",1831-07-04,"73 years, 67 days",James,NaN,...,58,310,1817-03-04,66,310,1825-03-04,6,122,73,67
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days",1848-02-23,"80 years, 227 days",John,Quincy,...,57,236,1825-03-04,61,236,1829-03-04,18,356,80,227
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days",1845-06-08,"78 years, 85 days",Andrew,NaN,...,61,354,1829-03-04,69,354,1837-03-04,8,96,78,85
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days",1862-07-24,"79 years, 231 days",Martin,Van,...,54,89,1837-03-04,58,89,1841-03-04,21,142,79,231
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,1841-04-04,"68 years, 54 days",William,H.,...,68,23,1841-03-04,NaN,NaN,NaT,NaN,NaN,68,54
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days",1862-01-18,"71 years, 295 days",John,NaN,...,51,6,1841-04-04,54,340,1845-03-04,16,320,71,295
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,1849-06-15,"53 years, 225 days",James,K.,...,49,122,1845-03-04,53,122,1849-03-04,NaN,NaN,53,225
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,1850-07-09,"65 years, 227 days",Zachary,NaN,...,64,100,1849-03-04,65,227,1850-07-09,NaN,NaN,65,227
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days",1874-03-08,"74 years, 60 days",Millard,NaN,...,50,183,1850-07-09,53,56,1853-03-04,21,4,74,60
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days",1869-10-08,"64 years, 319 days",Franklin,NaN,...,48,101,1853-03-04,52,101,1857-03-04,12,218,64,319
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days",1868-06-01,"77 years, 39 days",James,NaN,...,65,315,1857-03-04,69,315,1861-03-04,7,89,77,39
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,1865-04-15,"56 years, 62 days",Abraham,NaN,...,52,20,1861-03-04,56,62,1865-04-15,NaN,NaN,56,62
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days",1875-07-31,"66 years, 214 days",Andrew,NaN,...,56,107,1865-04-15,60,65,1869-03-04,6,149,66,214
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days",1885-07-23,"63 years, 87 days",Ulysses,S.,...,46,311,1869-03-04,54,311,1877-03-04,8,141,63,87
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days",1893-01-17,"70 years, 105 days",Rutherford,B.,...,54,151,1877-03-04,58,151,1881-03-04,11,319,70,105
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,1881-09-19,"49 years, 304 days",James,A.,...,49,105,1881-03-04,49,304,1881-09-19,NaN,NaN,49,304
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days",1886-11-18,"57 years, 44 days",Chester,A.,...,51,349,1881-09-19,55,150,1885-03-04,1,259,57,44
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]",1908-06-24,"71 years, 98 days",Grover,NaN,...,47,351,1885-03-04,51,351,1889-03-04,4,0,71,98
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days",1901-03-13,"67 years, 205 days",Benjamin,NaN,...,55,196,1889-03-04,59,196,1893-03-04,8,9,67,205
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]",1908-06-24,"71 years, 98 days",Grover,NaN,...,55,351,1893-03-04,59,351,1897-03-04,11,112,71,98
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,1901-09-14,"58 years, 228 days",William,NaN,...,54,34,1897-03-04,58,228,1901-09-14,NaN,NaN,58,228
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days",1919-01-06,"60 years, 71 days",Theodore,NaN,...,42,322,1901-09-14,50,128,1909-03-04,9,308,60,71
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days",1930-03-08,"72 years, 174 days",William,H.,...,51,170,1909-03-04,55,170,1913-03-04,17,4,72,174
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days",1924-02-03,"67 years, 37 days",Woodrow,NaN,...,56,66,1913-03-04,64,66,1921-03-04,2,336,67,37
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,1923-08-02,"57 years, 273 days",Warren,G.,...,55,122,1921-03-04,57,273,1923-08-02,NaN,NaN,57,273
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days",1933-01-05,"60 years, 185 days",Calvin,NaN,...,51,29,1923-08-02,56,243,1929-03-04,3,307,60,185
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days",1964-10-20,"90 years, 71 days",Herbert,NaN,...,54,206,1929-03-04,58,206,1933-03-04,31,230,90,71
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,1945-04-12,"63 years, 72 days",Franklin,D.,...,51,33,1933-03-04,63,72,1945-04-12,NaN,NaN,63,72
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days",1972-12-26,"88 years, 232 days",Harry,S.,...,60,339,1945-04-12,68,257,1953-01-20,19,341,88,232
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days",1969-03-28,"78 years, 165 days",Dwight,D.,...,62,98,1953-01-20,70,98,1961-01-20,8,67,78,165
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,1963-11-22,"46 years, 177 days",John,F.,...,43,236,1961-01-20,46,177,1963-11-22,NaN,NaN,46,177
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days",1973-01-22,"64 years, 148 days",Lyndon,B.,...,55,87,1963-11-22,60,146,1969-01-20,4,2,64,148
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days",1994-04-22,"81 years, 103 days",Richard,NaN,...,56,11,1969-01-20,61,212,1974-08-09,19,256,81,103
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days",2006-12-26,"93 years, 165 days",Gerald,NaN,...,61,26,1974-08-09,63,190,1977-01-20,29,340,93,165
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",NaT,"94 years, 286 days",Jimmy,NaN,...,52,111,1977-01-20,56,111,1981-01-20,38,175,94,286
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days",2004-06-05,"93 years, 120 days",Ronald,NaN,...,69,349,1981-01-20,77,349,1989-01-20,15,137,93,120
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days",2018-11-30,"94 years, 171 days",George,H.,...,64,222,1989-01-20,68,222,1993-01-20,25,314,94,171
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",NaT,"72 years, 329 days",Bill,NaN,...,46,154,1993-01-20,54,154,2001-01-20,18,175,72,329
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",NaT,"73 years, 8 days",George,W.,...,54,198,2001-01-20,62,198,2009-01-20,10,175,73,8
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",NaT,"57 years, 344 days",Barack,NaN,...,47,169,2009-01-20,55,169,2017-01-20,2,175,57,344